config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :trucks do
    resources :trips
  end
  
  root to: "trucks#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :truck
end

app/models/truck.rb
class Truck < ActiveRecord::Base
  has_many :trips

  searchkick

  def self.search(search)

    if search
      where(['plate LIKE ?', "%#{search}%"])
    else
      all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :set_truck

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all.limit(10)
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    @trip.truck_id = @truck.id

    if @trip.save
      redirect_to @truck
    else
      render 'new'
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    def set_truck
      @truck = Truck.find(params[:truck_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:date, :driver, :liter, :weight, :distance, :cement, :destination)
    end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.search(params[:search])
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
    @trips = Trip.where(truck_id: @truck.id)
    # @trips = Trip.where(truck_id: @truck.id).limit(10)
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render :show, status: :created, location: @truck }
      else
        format.html { render :new }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { render :show, status: :ok, location: @truck }
      else
        format.html { render :edit }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, notice: 'Truck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(:plate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <a class="navbar-brand"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; บริษัท สุมนยาสระบุรี (2001) ขนส่ง จำกัด &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <ul class="nav navbar-nav">
      <li><a href="/trucks"> หน้าแรก &nbsp;&nbsp; <span class="sr-only">(current)</span></a></li>
      <li><a href="/trucks"> ตั้งค่า <span class="sr-only">(current)</span></a></li>
    </ul>
  <ul class="nav navbar-nav navbar-right">
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
      </div>
      <form action="/trucks" accept-charset="UTF-8" method="get">
        <input name="utf8" type="hidden" value="✓">
        <input type="text" class="form-control" name="search" id="search-bar" placeholder="ค้นหาทะเบียนรถ...">
        <input type="submit" name="commit" value="ค้นหา" class="btn btn-default">
      </form>
    </form>
  </ul>
</nav>

app/views/layouts/application.html.erb
<p id="notice"><%= notice %></p>
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/header' %>
    <div class="container">
        <% flash.each do |name, msg| %>
    			<%= content_tag(:div, msg, class: "alert alert-info") %>
    		<% end %>
    		<%= yield %>
    </div>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<!-- Compiled and minified CSS -->

    <!-- Latest compiled and minified CSS -->

</body>

</html>

app/views/trips/_form.html.erb
<%= form_for([@truck, @trip]) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :"วันที่" %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :"พนักงานขับรถ" %><br>
    <%= f.text_field :driver %>
  </div>
  <div class="field">
    <%= f.label :"น้ำมัน(ลิตร)" %><br>
    <%= f.text_field :liter %>
  </div>
  <div class="field">
    <%= f.label :"น้ำหนัก(ตัน)" %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :"ระยะทาง" %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :"ชนิดปูน" %><br>
    <%= f.text_field :cement %>
  </div>
  <div class="field">
    <%= f.label :"สถานที่ส่งของ" %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

<div class="panel panel-default">
  <div class="panel-body">
<form autocomplete="on" class="new_trip" id="new_trip" action="/trucks/6/trips demo_form.asp" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="e6ZnbJX7kPU95FJ8smYshwu9aT9514p4WPgKFA8whuMMmfEv+Qq8MwifGRioWGjQxzPmsko2CtoDb3heI74XFQ==">

  <div class="field">
    <label for="trip_วันที่">วันที่</label><br>
    <input type="text" name="trip[date]" id="trip_date">
  </div>

  <div class="field">
    <label for="trip_พนักงานขับรถ">พนักงานขับรถ</label><br>
    <input type="text" name="trip[driver]" id="trip_driver">
  </div>
  <div class="field">
    <label for="trip_น้ำมัน(ลิตร)">น้ำมัน(ลิตร)</label><br>
    <input type="text" name="trip[liter]" id="trip_liter">
  </div>
  <div class="field">
    <label for="trip_น้ำหนัก(ตัน)">น้ำหนัก(ตัน)</label><br>
    <input type="text" name="trip[weight]" id="trip_weight">
  </div>
  <div class="field">
    <label for="trip_ระยะทาง">ระยะทาง</label><br>
    <input type="text" name="trip[distance]" id="trip_distance">
  </div>
  <div class="field">
    <label for="trip_ชนิดปูน">ชนิดปูน</label><br>
    <input type="text" name="trip[cement]" id="trip_cement">
  </div>
  <div class="field">
    <label for="trip_สถานที่ส่งของ">สถานที่ส่งของ</label><br>
    <input type="text" name="trip[destination]" id="trip_destination">
  </div>
  <div class="actions">
    <input type="submit" name="commit" value="Create Trip">
  </div>
</form>

  </div>
</div>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Driver</th>
      <th>Liter</th>
      <th>Weight</th>
      <th>Distance</th>
      <th>Cement</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.date %></td>
        <td><%= trip.driver %></td>
        <td><%= trip.liter %></td>
        <td><%= trip.weight %></td>
        <td><%= trip.distance %></td>
        <td><%= trip.cement %></td>
        <td><%= trip.destination %></td>
        <td>ssss<%= link_to 'Show', trip %></td>

        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %> -->

app/views/trips/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', truck_path(@truck) %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @trip.date %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @trip.driver %>
</p>

<p>
  <strong>Liter:</strong>
  <%= @trip.liter %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @trip.weight %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @trip.distance %>
</p>

<p>
  <strong>Cement:</strong>
  <%= @trip.cement %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @trip.destination %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<!-- <%= link_to 'Back', truck_path(@truck) %> -->

app/views/trucks/_form.html.erb
<%= form_for(@truck) do |f| %>
  <% if @truck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@truck.errors.count, "error") %> prohibited this truck from being saved:</h2>

      <ul>
      <% @truck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <label for="truck_plate">Plate</label><br>
      <textarea name="truck[plate]" id="truck_plate"></textarea>
  </div>

  <div class="actions">
      <input type="submit" name="commit" value="Create Truck">
  </div>  
<% end %>

app/views/trucks/edit.html.erb
<h1>Editing Truck</h1>

<%= render 'form' %>

<%= link_to 'Show', @truck %> |
<%= link_to 'Back', trucks_path %>

app/views/trucks/index.html.erb
<p id="notice"><%= notice %></p>

<h1></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <td align="center">ทะเบียนรถ</td>
      <td align="center">น้ำมันเครื่อง</td>
      <td align="center">น้ำมันเกียร์</td>
      <td align="center">เฟืองท้าย</td>
      <td align="center">กรองอากาศ</td>
      <td colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trucks.each do |truck| %>
      <tr>
        <td align="center"><%= truck.plate %></td>
        <!-- <script>
          console.log("<%= truck.plate %>")
        </script> -->
        <td align="center"><svg height="23" width="23">
              <circle cx="11.5" cy="11.5" r="11.5" fill="#00FF00" />
            </svg>
        </td>
        <td align="center"><svg height="23" width="23">
              <circle cx="11.5" cy="11.5" r="11.5" fill="#00FF00" />
            </svg>
        </td align="center">
        <td align="center"><svg height="23" width="23">
              <circle cx="11.5" cy="11.5" r="11.5" fill="#00FF00" />
            </svg>
        </td>
        <td align="center"><svg height="23" width="23">
              <circle cx="11.5" cy="11.5" r="11.5" fill="#00FF00" />
            </svg>
        </td>
        <td align="right"><%= link_to 'ดูข้อมูล', truck %></td>
        <td align="center"><%= link_to 'เพิ่มเที่ยว',  new_truck_trip_path(truck) %></td>
        <!-- <td><%= link_to 'Edit', edit_truck_path(truck) %></td> -->
        <!-- <td><%= link_to 'Destroy', truck, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Truck', new_truck_path %> -->

<a class="waves-effect waves-light btn" href="/trucks/new">เพิ่มรถ</a>

app/views/trucks/new.html.erb
<h1>New Truck</h1>

<%= render 'form' %>

<%= link_to 'Back', trucks_path %>

app/views/trucks/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>ทะเบียนรถ:</strong>
  <%= @truck.plate %>
</h3>

<br>

<div class="progress">
  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
    <!-- <span class="sr-only">40% Complete (success)</span> -->
    น้ำมันเครื่อง 40%
  </div>
</div>



<div class="progress">
  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width: 15%">
    <!-- <span class="sr-only">20% Complete</span> -->
    น้ำมันเกียร์ 15%
  </div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
    <!-- <span class="sr-only">60% Complete (warning)</span> -->
    น้ำมันเฟืองท้าย 60%
  </div>
</div>
<div class="progress">
  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
    <!-- <span class="sr-only">80% Complete (danger)</span> -->
    กรองอะกาศ 80%
  </div>
</div>


<br>
<table id="text-center" class="table table-striped">
  <thead>
    <tr>
      <th>วันที่</th>
      <th>พนักงานขับรถ</th>
      <th>น้ำมัน/ลิตร</th>
      <th>จำนวนตัน</th>
      <th>ระยะทาง</th>
      <th>ชนิดปูน</th>
      <th>สถานที่ส่งของ</th>
    </tr>
  </thead>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.date %></td>
    <td><%= trip.driver %></td>
    <td><%= trip.liter %></td>
    <td><%= trip.weight %></td>
    <td><%= trip.distance %></td>
    <td><%= trip.cement %></td>
    <td><%= trip.destination %></td>
  

  </tr>
<% end %>
</table>


<br>
<%= link_to 'create', new_truck_trip_path(@truck) %> |
<%= link_to 'Edit', edit_truck_path(@truck) %> |
<%= link_to 'Back', trucks_path %>